spring:
  data:
    elasticsearch:
      cluster-name: ${db.elasticsearch.cluster-name}
      cluster-nodes: ${db.elasticsearch.cluster-nodes}

zlt:
  indices:
    show: sys-log-*, mysql-slowlog-*, sys_user, point-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: com.central.search.controller